name: deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-1
  SYSTEM_NAME: example
  SERVICE_NAME: foobar

jobs:
  deploy:
    name: Test Action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2     
      - name: Set env vars for prod
        run: |
          echo "ENV_1=test" >> $GITHUB_ENV
#          echo "VPC_CIDR=172.31.0.0/16" 
        if: github.ref == 'refs/heads/main'

      - name: Set env vars for prod
        run: |
          echo "branch=$ENV_1 "
